# Generated by Django 3.2.6 on 2021-08-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobrevivente', '0002_auto_20210825_1752'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sinalizarcontaminado',
            name='Restrição',
        ),
    ]
